use customer_behavior;

-- 1. what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from cust_info
group by gender;

-- 2. which customer used discount but still spent more then the average purchase?

select customer_id,purchase_amount
from cust_info
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from cust_info);

-- 3. which are the top 5 products with the highest average review ratng?

select item_purchased,round(avg(review_rating),2) as average_product_rating
from cust_info
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. compare the average purchase amounts between standard and exprass shipping?

select shipping_type,round(avg(purchase_amount),2)
from cust_info
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5. do subscribed customers spend more? compare average spend and total revenue between subscribred and non-subscribed

select subscription_status,count(customer_id) as total_cust,round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from cust_info
group by subscription_status
order by total_revenue,avg_spend desc;